# Analise de sistemas lineares 
### Instituição: Ilum Escola de Ciência
   ### Aluno: Ricardo Pereira Lourenço de Carvalho
   ### Docentes: Daniel R. Cassar, Leandro N. Lemos, James M. de Almeida

Este programa em python busca solucionar sistemas lineares 3x3 e 2x2, covertendo os em matrizes 3X4 e matrizes 2x3 respectivamente.
Assim, os metodos de calculo utilizados neste código se baseiam em matrizes triangulares como o método de eliminação de Gauss.
    
Ao final das seções Sistemas Lineares 2x2 e 3x3 existem seus respectivos sumários contendo informações da matriz inicial, tipo do sistema, determinantes e suas soluções caso existam.

## Exemplo de Sistema Linear

O sistema linear:


\begin{cases}
1x + 2y + 3z = 11 \\
3x + 2y + 1z = 9 \\
2x + 3y + 1z = 10
\end{cases}


tem como representação matricial:
                        

$$
M =
\begin{bmatrix}
1 & 2 & 3 & 11 \\
3 & 2 & 1 & 9 \\
2 & 3 & 1 & 10
\end{bmatrix}
$$




OBS: dirija-se a seção Sistema Linear 2x2 caso se deseje calcular um sistema 2X2 como:

\begin{cases}
1x + 2y = 10 \\
2x - 1y = 5 \\
\end{cases}              


# Sistemas lineares 2x2

## Escolha seu sistema 2x2

Coloque seu sistema na celula abaixo, toda essa seção se baseará nesta matriz  

In [1]:
'''
O valor do elemento 1x1 da matriz pode ser acessado como M[0][0] 
e o elemento 2x2 como M[1][1] e assim sucetivamente

Abaixo está um sistema padrão.
Atribua as informações do seu sistema à matriz abaixo.
'''
M_2x2 = [
    [ 1 , 2 , 10 ],
    [ 2 , -1 , 5 ],
]

## Modulo Numpy

In [2]:
#importar a função set_printoptions para que os elementos das matrizes não se apresentem em notação científica
from numpy import set_printoptions

set_printoptions(suppress=True, precision=2)

#será usado a função array do  modulo numpy para transformar as listas em uma matriz
from numpy import array

## Transformar a matriz em uma matriz triangular

O processo de transformar a matriz em uma matriz triangular é essencial, pois facilita o calculo computacional.
Neste sentido matrizes triangulares são aquelas que seguem o seguinte formato:

$$
M =
\begin{bmatrix}
a & b  \\
0 & c \\
\end{bmatrix}
$$

In [3]:
# transformação da lista em uma matriz pela função array
M_2x2 = array(M_2x2, dtype = float)

#Nova matriz para que não haja perca de informações
matriz_copia_2x2 = M_2x2.copy()

Antes de qualquer passo, verificaremos se a primeira coluna da matriz é zero
ou se o elemento 1x1 é zero.

Apos isso será necessario dividir a primeira linha da matriz pelo seu primeiro elemento.
E depois subtrir a linha 2 pela linha 1, para que tenhamos o primeiro 
digito da segunda linha como 0.

In [4]:
# para o calculo da determinante sera armazenado a variavel troca
troca_2x2 = 0


# Caso toda a primeira coluna seja composta por zeros nada acontece
if all(linha[0] == 0 for linha in matriz_copia_2x2):

    linha1 = None
    
else:
    # Caso o primeiro elemento da matriz seja 0, realizar uma troca das linhas por um valor nâo nulo    
    if matriz_copia_2x2[0][0] == 0:

        for i in range(1,2):

            if matriz_copia_2x2[i][0] != 0:

                matriz_copia_2x2[[0,i]] = matriz_copia_2x2[[i,0]]
                troca_2x2 += 1
                break
            

    # Armazenar o elemento 1x1 original
    elemento_original_1x1_da_matriz_2x2 = matriz_copia_2x2[0][0]

    # Dividir todos os elementos da primeira linha pelo elemento 1x1 da matriz: Assim o elemento 1x1 = 1         
    linha1 = matriz_copia_2x2[0]/matriz_copia_2x2[0][0]

    # Substituir a linha 1  subtrair a linha 2 pela linha 1 multiplicada pelo elemento 2x1
    matriz_copia_2x2[0] = linha1
    
    #visualize
    print("Matriz antes da subtração:")
    print(matriz_copia_2x2)
    
    # subtrair a linha 2 pela linha 1 multiplicada pelo elemento 2x1
    matriz_copia_2x2[1]= matriz_copia_2x2[1] - matriz_copia_2x2[0]*matriz_copia_2x2[1][0]
    
#Armazenar o elemento caso a coluna seja composta por zeros
if matriz_copia_2x2[0][0] == 0:
    elemento_original_1x1_da_matriz_2x2 = matriz_copia_2x2[0][0]

#visualize
print("")
print("Matriz de após a subtração")
print(matriz_copia_2x2)

Matriz antes da subtração:
[[ 1.  2. 10.]
 [ 2. -1.  5.]]

Matriz de após a subtração
[[  1.   2.  10.]
 [  0.  -5. -15.]]


**Portanto agora obtivemos uma matriz triangular 2x2 (desconsiderando os resultados do sistema)**

## Descobir a determinante da matriz 2x2
O calculo da determinante é realizado pela multiplicação da diagonal principal vezes -1 elevado ao numero de trocas de linhas

In [5]:
def determinante_2x2(M):
    """
    Arg: Matriz triangular 2x2
    
    Essa função apenas funciona para matrizes triangulares 2x2, 
    visto que a ultima coluna 
    corrsponde as respostas do sistema
    
    Return: um float do determinante de matriz 
    """
    determinante = M[0][0]
    for linha in range (1, len(M)):
        determinante *= M[linha][linha]
        
    #Compensamos a divisao realizada anteriormente para criar a matriz triangular
    determinante = determinante * elemento_original_1x1_da_matriz_2x2 * ((-1)**troca_2x2)
    
    return determinante

In [6]:
#visualize
print(f"sua determinante é {determinante_2x2(matriz_copia_2x2)}")

sua determinante é -5.0


## Descobir se o sistema 2x2 é possivel determinado, possivel indeterminado ou impossivel

In [7]:
def tipo_sistema_2x2(M):
    '''
    Arg: Uma matriz triangular 2X2
    
    Contem os mesmos requisistos para o calculo da determinante
    
    Return: Uma string que expressa o tipo do sistema
    
    
    
    '''
    if determinante_2x2(M) == 0:
        # Caso uma linha seja compostas apenas por zeros o sistema é indeterminado
        if all(x == 0 for x in M[0]):
            return "Seu sistema é possivel indeterminado"              
        elif all(x == 0 for x in M[1]):
            return "Seu sistema é possivel indeterminado"   
            
        # Caso não, ele é impossivel
        else:
            return "Seu sistema é impossivel"
    else:
        return "Seu sistema é possivel determinado"


In [8]:
print(tipo_sistema_2x2(matriz_copia_2x2))

Seu sistema é possivel determinado


## Descobir as soluções do sistema 2x2

In [9]:
def respostas_sistema_2x2(M):
    '''
    Arg: Matriz triangular 3X3 
    As mesmas restrições que se aplicam as funções anterores
    
    Retrun: Dicionario contendo as respostas 
    caso a função seja possivel determinada
    Ou None caso não haja soluções
    
    '''

    
    if tipo_sistema_2x2(M) == "Seu sistema é possivel indeterminado":
        return None
    elif tipo_sistema_2x2(M) == "Seu sistema é impossivel":
        return None
    else:
        respostas = {}
        
        y = M[1][2]/ M[1][1]
        x = (M[0][2] - M[0][1]*y ) / M[0][0]
        
        respostas["x"], respostas["y"] = x,y
        return respostas

In [10]:
#visualize
print(respostas_sistema_2x2(matriz_copia_2x2))

{'x': np.float64(4.0), 'y': np.float64(3.0)}


## Sumario do Sistema linear 2x2
Infromações gerais sobre o sistema

In [11]:
"""
Exibe um resumo final do sistema.

Mostra:
sistema original
determinante
classificação
soluções (caso existam)
"""

print(f"Seu sistema inicial é:\n{M_2x2}")
print("")
print(f"A determinante da matriz é {determinante_2x2(matriz_copia_2x2)}")

print("")
print(tipo_sistema_2x2(matriz_copia_2x2))
print("")

if respostas_sistema_2x2(matriz_copia_2x2) is not None:

    print(f"Suas variáveis x, y e z são respectivamente:")

    print( f"x = {respostas_sistema_2x2(matriz_copia_2x2)['x']}" )

    print(f"y = {respostas_sistema_2x2(matriz_copia_2x2)['y']}")
else:
    print("Não foram encontradas soluções ao seu sistema")

Seu sistema inicial é:
[[ 1.  2. 10.]
 [ 2. -1.  5.]]

A determinante da matriz é -5.0

Seu sistema é possivel determinado

Suas variáveis x, y e z são respectivamente:
x = 4.0
y = 3.0


# Sistema Linear 3x3
Tem como exemplo novamente: 
$$
M =
\begin{bmatrix}
1 & 2 & 3 & 11 \\
3 & 2 & 1 & 9 \\
2 & 3 & 1 & 10
\end{bmatrix}
$$

## Escolha seu sistema 3x3

Coloque seu sistema na celula abaixo, toda essa seção se baseará nesta matriz


O valor do elemento 1x1 da matriz pode ser acessado como M[0][0] 
e o elemento 2x2 como M[1][1] e assim sucetivamente

In [12]:
''' 
Abaixo esta um sistema padrão.
Atribua as informações do seu sistema à matriz abaixo.
'''
M_3x3 = [
    [1 , 2 , 3 , 11],
    [3 , 2 , 1 , 9 ],
    [2 , 3 , 1 , 10]
]

## Modulo Numpy

In [13]:
#importar a função set_printoptions para que os elementos das matrizes não se apresentem em notação científica
from numpy import set_printoptions

set_printoptions(suppress=True, precision=2)

#será usado a função array do  modulo numpy para transformar as listas em uma matriz
from numpy import array

## Transformar a matriz em uma matriz triangular

O processo de transformar a matriz em uma matriz triangular é essencial, pois facilita o calculo computacional.
Neste sentido matrizes triangulares são aquelas que seguem o seguinte formato:

$$
M =
\begin{bmatrix}
a & b & c \\
0 & d & e \\
0 & 0 & f
\end{bmatrix}
$$

In [14]:
# transformação da lista em uma matriz pela função array
M_3x3 = array(M_3x3, dtype = float)

# Nova matriz para que não haja perca de informações
matriz_copia_3x3 = M_3x3.copy()


Antes de qualquer passo, verificaremos se a primeira coluna da matriz é zero
ou se o elemento 1x1 é zero.

Apos isso será necessario dividir a primeira linha da matriz pelo seu primeiro elemento.
E depois subtrir a linha 2 pela linha 1, para que tenhamos o primeiro 
digito da segunda linha como 0.



In [15]:
#para o calculo da determinante sera armazenado a variavel troca
troca_3x3 = 0

# Caso toda a primeira coluna seja composta por zeros nada acontece
if all(linha[0] == 0 for linha in matriz_copia_3x3):

    linha1 = None
    
else:
    # Caso o primeiro elemento da matriz seja 0, realizar uma troca das linhas até um valor nâo nulo    
    if matriz_copia_3x3[0][0] == 0:

        for i in range(1,3):

            if matriz_copia_3x3[i][0] != 0:

                matriz_copia_3x3[[0,i]] = matriz_copia_3x3[[i,0]]
                troca_3x3 += 1
                break
            

    # Armazenar o elemento 1x1 original
    elemento_original_1x1_da_natriz_3x3 = matriz_copia_3x3[0][0]

    # Dividir todos os elementos da primeira linha pelo elemento 1x1 da matriz: Assim o elemento 1x1 = 1         
    linha1 = matriz_copia_3x3[0]/matriz_copia_3x3[0][0]

    # Substituir a linha 1  subtrair a linha 2 pela linha 1 multiplicada pelo elemento 2x1
    matriz_copia_3x3[0] = linha1
    
    #visualize
    print("Matriz antes da subtração:")
    print(matriz_copia_3x3)

    # subtrair a linha 2 pela linha 1 multiplicada pelo elemento 2x1
    matriz_copia_3x3[1]= matriz_copia_3x3[1] - matriz_copia_3x3[0]*matriz_copia_3x3[1][0]

#Armazenar o elemento caso a coluna seja composta por zeros
if matriz_copia_3x3[0][0] == 0:
    elemento_original_1x1_da_natriz_3x3 = matriz_copia_3x3[0][0]

#visualize
print("")
print("Matriz de após a subtração")
print(matriz_copia_3x3)

Matriz antes da subtração:
[[ 1.  2.  3. 11.]
 [ 3.  2.  1.  9.]
 [ 2.  3.  1. 10.]]

Matriz de após a subtração
[[  1.   2.   3.  11.]
 [  0.  -4.  -8. -24.]
 [  2.   3.   1.  10.]]


In [16]:
'''
Agora tornaremos 0 o elemento 3x1 da matriz
'''
#subtrair a linha 3 da matriz pela linha 1 multiplicada pelo elemento 3x1
matriz_copia_3x3[2] = matriz_copia_3x3[2] - matriz_copia_3x3[0]*matriz_copia_3x3[2][0]

#visualize
print("Seu sistema após a subtração")
print(matriz_copia_3x3)

Seu sistema após a subtração
[[  1.   2.   3.  11.]
 [  0.  -4.  -8. -24.]
 [  0.  -1.  -5. -12.]]



Primeiramente , verificaremos se a segunda coluna da matriz é composta de zeros
ou se o elemento 2x2 é zero.

Da mesma forma que fizemos anteriormente,
tornaremos 1 o segundo termo da segunda fileira (2x2)
fileira, dividindo a linha por ele mesmo.

E subtrairemos a linha 3 pela linha 2.

In [17]:
# caso a segunda coluna seja composta apenas por zeros, nada acontece
if all(linha[1] == 0 for linha in matriz_copia_3x3):

    linha2 = None
# caso o elemnto 2x2 da matriz seja 0, realizar uma troca das linhas
else:
    if matriz_copia_3x3[1][1] == 0:
        
        for i in range(2, len(matriz_copia_3x3)):
            
            if matriz_copia_3x3[i][1] != 0:
                matriz_copia_3x3[[1, i]] = matriz_copia_3x3[[i, 1]]
                troca_3x3 += 1
                
                break
                
    #Armazenar o elemento 2x2
    elemento_original_2x2_da_matriz_3x3 = matriz_copia_3x3[1][1]

    #Dividir todos os elementos da segunda linha pelo elemento 2x2 da matriz: Assim o elemento 2x2 = 1
    if matriz_copia_3x3[1][1] != 0:
        linha2 = matriz_copia_3x3[1] / matriz_copia_3x3[1][1]
    else:
        linha2 = matriz_copia_3x3[1]

    #substituir a linha 2
    matriz_copia_3x3[1] = linha2

    #visualize
    print("Matriz antes da subtração:")
    print(matriz_copia_3x3)
    print("")

    #subtrair a linha 3 pela linha 2 multiplicada pelo elemento 3x2
    matriz_copia_3x3[2] = matriz_copia_3x3[2] - matriz_copia_3x3[1]*matriz_copia_3x3[2][1]

#Armazenar o elemento caso a coluna seja composta por zeros
if matriz_copia_3x3[1][1] == 0:
    elemento_original_2x2_da_matriz_3x3 = matriz_copia_3x3[1][1]

#visualize
print("Matriz de após a subtração")
print(matriz_copia_3x3)

Matriz antes da subtração:
[[  1.   2.   3.  11.]
 [ -0.   1.   2.   6.]
 [  0.  -1.  -5. -12.]]

Matriz de após a subtração
[[ 1.  2.  3. 11.]
 [-0.  1.  2.  6.]
 [ 0.  0. -3. -6.]]


**Portanto agora obtivemos uma matriz triangular 3x3 (desconsiderando os resultados do sistema)**

## Descobir a determinante da matriz 3x3
O calculo da determinante é realizado pela multiplicação da diagonal principal vezes -1 elevado ao numero de trocas de linhas

In [18]:
def determinante_3x3(M):
    """
    Arg: Matriz triangular
    
    Essa função apenas funciona para matrizes triangulares 2x2, 
    visto que a ultima coluna 
    corrsponde as respostas do sistema
    
    Return: um float do determinante de matriz 
    """
    determinante = M[0][0]
    for linha in range (1, len(M)):
        determinante *= M[linha][linha]
        
    #Compensamos a divisao realizada anteriormente para criar a matriz triangular
    determinante = determinante * elemento_original_1x1_da_natriz_3x3 * elemento_original_2x2_da_matriz_3x3 * ((-1)**troca_3x3)
    
    return determinante

In [19]:
#Visualize
print(f"sua determinante é {determinante_3x3(matriz_copia_3x3)}")

sua determinante é 12.0


## Descobir se o sistema 3x3 é possivel determinado, possivel indeterminado ou impossivel

In [20]:
def tipo_sistema_3x3(M):
    '''
    Arg: Uma matriz triangular 3X3
    
    Contem os mesmos requisistos para o calculo da determinante
    
    Return: Uma string que expressa o tipo do sistema
    
    
    
    '''
    if determinante_3x3(M) == 0:
        #Caso uma linha seja compostas apenas por zeros o sistema é indeterminado
        if all(x == 0 for x in M[0]):
            return "Seu sistema é possivel indeterminado"  
            
        elif all(x == 0 for x in M[1]):
            return "Seu sistema é possivel indeterminado"
            
        elif all(x == 0 for x in M[2]):
            return "Seu sistema é possivel indeterminado"
        # Caso nãom é impossivel
        else:
            return "Seu sistema é impossivel"
    else:
        return "Seu sistema é possivel determinado"
    

In [21]:
#visualize
print(tipo_sistema_3x3(matriz_copia_3x3))
print(matriz_copia_3x3)

Seu sistema é possivel determinado
[[ 1.  2.  3. 11.]
 [-0.  1.  2.  6.]
 [ 0.  0. -3. -6.]]


## Descobir as soluções do sistema 3x3

In [22]:
def respostas_sistema_3x3(M):
    '''
    Arg: Matriz triangular 3X3 
    As mesmas restrições que se aplicam as funções anterores
    
    Retrun: Dicionario contendo as respostas 
    caso a função seja possivel determinada
    Ou None caso não haja soluções
    
    '''

    
    if tipo_sistema_3x3(M) == "Seu sistema é possivel indeterminado":
        return None
    elif tipo_sistema_3x3(M) == "Seu sistema é impossivel":
        return None
    else:
        respostas = {}
        z = M[2][3] / M[2][2]
        y = (M[1][3] - M[1][2]*z) / M[1][1]
        x = (M[0][3] - M[0][1]*y - M[0][2]*z) / M[0][0]
        
        respostas["x"], respostas["y"], respostas["z"] = x,y,z
        return respostas

In [23]:
#visualize
print(respostas_sistema_3x3(matriz_copia_3x3))

{'x': np.float64(1.0), 'y': np.float64(2.0), 'z': np.float64(2.0)}


## Sumario do Sistema linear 3x3
Infromações gerais sobre o sistema

In [24]:
"""
Exibe um resumo final do sistema.

Mostra:
sistema original
determinante
classificação
soluções (caso existam)
"""

print(f"Seu sistema inicial é:\n{M_3x3}")
print("")
print(f"A determinante da matriz é {determinante_3x3(matriz_copia_3x3)}")
print("")
print(tipo_sistema_3x3(matriz_copia_3x3))
print("")

if respostas_sistema_3x3(matriz_copia_3x3) is not None:

    print(f"Suas variáveis x, y e z são respectivamente:")
    print(f"x = {respostas_sistema_3x3(matriz_copia_3x3)['x']}") 
    print(f"y = {respostas_sistema_3x3(matriz_copia_3x3)['y']}")
    print(f"z = {respostas_sistema_3x3(matriz_copia_3x3)['z']}")
else:
    print("Não foram encontradas soluções ao seu sistema")

Seu sistema inicial é:
[[ 1.  2.  3. 11.]
 [ 3.  2.  1.  9.]
 [ 2.  3.  1. 10.]]

A determinante da matriz é 12.0

Seu sistema é possivel determinado

Suas variáveis x, y e z são respectivamente:
x = 1.0
y = 2.0
z = 2.0
