# Analise de sistemas lineares 3x3
### Instituição: Ilum Escola de Ciência
   ### Aluno: Ricardo Pereira Lourenço de Carvalho
   ### Docentes: Daniel R. Cassar, Leandro N. Lemos, James M. de Almeida

Este programa em python busca solucionar sistemas lineares distintos, covertendo os em matrizes 3X4.
Contudo os metodos de calculo utilizados se baseiam em matrizes triangulares como o método de eliminação de Gauss.
    
Ao final do codigo existe um sumário contendo informações da matriz inicial, tipo do sistema, determinantes e suas soluções caso existam. Caso se deseje rodar todas as celulas de uma vez.

## Exemplo de Sistema Linear

O sistema linear:


\begin{cases}
1x + 2y + 3z = 11 \\
3x + 2y + 1z = 9 \\
2x + 3y + 1z = 10
\end{cases}


tem como representação matricial:
                        

$$
M =
\begin{bmatrix}
1 & 2 & 3 & 11 \\
3 & 2 & 1 & 9 \\
2 & 3 & 1 & 10
\end{bmatrix}
$$




Caso se deseje se utilizar de um sistema 2X2 como:

                        1x + 2y = 10
                        2x - 1y = 5


## Escolha seu sistema

coloque seu sistema na celula abaixo, todo o codigo se baseará nesta matriz

In [1]:
'''
O valor do elemento 1x1 da matriz pode ser acessado como M[0][0] 
e o elemento 2x2 como M[1][1] e assim sucetivamente

Abaixo esta um sistema padrão.
Atribua as informações do seu sistema à matriz abaixo.
'''
M = [
    [0,1,1,2],
    [0,2,2,4],
    [0,3,3,6]
]

## Modulo Numpy

In [2]:
#importar a função set_printoptions para que as matrizes não se apresentem em notação científica
from numpy import set_printoptions

set_printoptions(suppress=True, precision=2)

#será usado a função array do  modulo numpy para transformar as listas em uma matriz
from numpy import array

## Transformar a matriz em uma matriz triangular

O processo de transformar a matriz em uma matriz triangular é essencial, pois facilita o calculo computacional.
Neste sentido matrizes triangulares são aquelas que seguem o seguinte formato:

$$
M =
\begin{bmatrix}
a & b & c \\
0 & d & e \\
0 & 0 & f
\end{bmatrix}
$$

In [3]:
# transformação da lista em uma matriz pela função array
M = array(M, dtype = float)

#Nova matriz para que não haja perca de informações
matriz_copia = M.copy()

In [4]:
'''
Antes de qualquer passo, armazenaremos o elemento 1x1 para o futuro calculo do determinante 
da matriz 3x3 (Matriz sem as respostas do sistema).

Apos isso será necessario dividir a primeira linha da matriz pelo seu primeiro elemento.
E depois subtrir a linha 2 pela linha 1, para que tenhamos o primeiro 
digito da segunda linha como 0.

'''
#para o calculo da determinante sera armazenado a variavel troca
troca = 0


# Caso toda a primeira coluna seja composta por zeros nada acontece
if all(linha[0] == 0 for linha in matriz_copia):

    linha1 = None
    
else:
    # Caso o primeiro elemento da matriz seja 0, realizar uma troca das linhas até um valor nâo nulo    
    if matriz_copia[0][0] == 0:

        for i in range(1,3):

            if matriz_copia[i][0] != 0:

                matriz_copia[[0,i]] = matriz_copia[[i,0]]
                troca += 1
                break
            

    # Armazenar o elemento 1x1 original
    elemento_original_1x1 = matriz_copia[0][0]

    # Dividir todos os elementos da primeira linha pelo elemento 1x1 da matriz: Assim o elemento 1x1 = 1         
    linha1 = matriz_copia[0]/matriz_copia[0][0]

    # Substituir a linha 1  subtrair a linha 2 pela linha 1 multiplicada pelo elemento 2x1
    matriz_copia[0] = linha1

    # subtrair a linha 2 pela linha 1 multiplicada pelo elemento 2x1
    matriz_copia[1]= matriz_copia[1] - matriz_copia[0]*matriz_copia[1][0]
    
if matriz_copia[0][0] == 0:
    elemento_original_1x1 = matriz_copia[0][0]

#visualize
print(matriz_copia)

[[0. 1. 1. 2.]
 [0. 2. 2. 4.]
 [0. 3. 3. 6.]]


In [5]:
'''
Agora tornaremos 0 o elemento 3x1 da matriz
'''
#subtrair a linha 3 da matriz pela linha 1 multiplicada pelo elemento 3x1
matriz_copia[2] = matriz_copia[2] - matriz_copia[0]*matriz_copia[2][0]

#visualize
print(matriz_copia)

[[0. 1. 1. 2.]
 [0. 2. 2. 4.]
 [0. 3. 3. 6.]]


In [6]:
'''
Primeiramente armazenaremos o elemento 2x2 para o futuro calculo do determinante.

Da mesma forma que fizemos anteriormente,
tornaremos 1 o segundo termo da segunda fileira (2x2)
fileira, dividindo a linha por ele mesmo.

E subtrairemos a linha 3 pela linha 2.

'''
# caso a segunda coluna seja composta apenas por zeros, nada acontece
if all(linha[1] == 0 for linha in matriz_copia):

    linha2 = None
# caso o elemnto 2x2 da matriz seja 0, realizar uma troca das linhas
else:
    if matriz_copia[1][1] == 0:
        
        for i in range(2, len(matriz_copia)):
            
            if matriz_copia[i][1] != 0:
                matriz_copia[[1, i]] = matriz_copia[[i, 1]]
                troca += 1
                
                break
                
                

    #Armazenar o elemento 2x2
    elemento_original_2x2 = matriz_copia[1][1]

    #Dividir todos os elementos da segunda linha pelo elemento 2x2 da matriz: Assim o elemento 2x2 = 1
    if matriz_copia[1][1] != 0:
        linha2 = matriz_copia[1] / matriz_copia[1][1]
    else:
        linha2 = matriz_copia[1]

    #substituir a linha 2
    matriz_copia[1] = linha2

    #visualize
    print(matriz_copia)
    print("")

    #subtrair a linha 3 pela linha 2 multiplicada pelo elemento 3x2
    matriz_copia[2] = matriz_copia[2] - matriz_copia[1]*matriz_copia[2][1]
    
if matriz_copia[1][1] == 0:
    elemento_original_2x2 = matriz_copia[1][1]

#visualize
print(matriz_copia)

[[0. 1. 1. 2.]
 [0. 1. 1. 2.]
 [0. 3. 3. 6.]]

[[0. 1. 1. 2.]
 [0. 1. 1. 2.]
 [0. 0. 0. 0.]]


**Portanto agora obtivemos uma matriz triangular 3x3 (desconsiderando os resultados do sistema)**

## Descobir o determinante da matriz

In [7]:
def determinante_3x3(M):
    """
    Arg: Matriz triangular
    
    Essa função apenas funciona para matrizes triangulares 3x3, 
    visto que a ultima coluna 
    corrsponde as respostas do sistema
    
    Return: um float do determinante de matriz 
    """
    determinante = M[0][0]
    for linha in range (1, len(M)):
        determinante *= M[linha][linha]
        
    #Compensamos a divisao realizada anteriormente para criar a matriz triangular
    determinante = determinante * elemento_original_1x1 * elemento_original_2x2 * ((-1)**troca)
    
    return determinante

In [8]:
#visualize
print(determinante_3x3(matriz_copia))

0.0


## Descobir se a função é possivel determinada, possivel indeterminada ou impossivel

In [9]:
def tipo_sistema_3x3(M):
    '''
    Arg: Uma matriz triangular 3X3
    Contem os mesmos requisistos para o calculo da determinante
    Return: Uma string que expressa o tipo do sistema
    
    
    
    '''
    if determinante_3x3(M) == 0:
        #Caso uma linha seja compostas apenas por zeros o sistema é indeterminado
        if all(x == 0 for x in matriz_copia[0]):
            return "Seu sistema é possivel indeterminado"  
            
        elif all(x == 0 for x in matriz_copia[1]):
            return "Seu sistema é possivel indeterminado"
            
        elif all(x == 0 for x in matriz_copia[2]):
            return "Seu sistema é possivel indeterminado"
            
        else:
            return "Seu sistema é impossivel"
    else:
        return "Seu sistema é possivel determinado"
    

In [10]:
#visualize
print(tipo_sistema_3x3(matriz_copia))
print(matriz_copia)

Seu sistema é possivel indeterminado
[[0. 1. 1. 2.]
 [0. 1. 1. 2.]
 [0. 0. 0. 0.]]


## Descobir as soluções do sistema

In [11]:
def respostas_sistema_3x3(M):
    '''
    Arg: Matriz triangular 3X3 
    As mesmas restrições que se aplicam as funções anterores
    
    Retrun: Dicionario contendo as respostas 
    caso a função seja possivel determinada
    Ou None caso não haja soluções
    
    '''

    
    if tipo_sistema_3x3(M) == "Seu sistema é possivel indeterminado":
        return None
    elif tipo_sistema_3x3(M) == "Seu sistema é impossivel":
        return None
    else:
        respostas = {}
        z = M[2][3] / M[2][2]
        y = (M[1][3] - M[1][2]*z) / M[1][1]
        x = (M[0][3] - M[0][1]*y - M[0][2]*z) / M[0][0]
        
        respostas["x"], respostas["y"], respostas["z"] = x,y,z
        return respostas

In [12]:
#visualize
print(respostas_sistema_3x3(matriz_copia))

None


# Sumario do Sistema linear 3x3
Infromações gerais sobre o sistema

In [13]:
"""
Exibe um resumo final do sistema.

Mostra:
sistema original
determinante
classificação
soluções (caso existam)
"""

print(f"Seu sistema inicial é:\n{M}")
print("")
print(f"A determinante da matriz é {determinante_3x3(matriz_copia)}")

print("")
print(tipo_sistema_3x3(matriz_copia))
print("")

if respostas_sistema_3x3(matriz_copia) is not None:

    print(
        f"Suas variáveis x, y e z são respectivamente:")

    print(
        f"x = {respostas_sistema_3x3(matriz_copia)['x']}"
    )

    print(
        f"y = {respostas_sistema_3x3(matriz_copia)['y']}"
    )

    print(
        f"z = {respostas_sistema_3x3(matriz_copia)['z']}"
    )
else:
    print("Não foram encontradas soluções ao seu sistema")

Seu sistema inicial é:
[[0. 1. 1. 2.]
 [0. 2. 2. 4.]
 [0. 3. 3. 6.]]

A determinante da matriz é 0.0

Seu sistema é possivel indeterminado

Não foram encontradas soluções ao seu sistema
