# Analise de sistemas lineares


Este programa em python busca solucionar sistemas lineares distintos para a matriz 3X3 desejada 

## Matriz de teste

#### será usado a função array do  modulo numpy para transformar as listas em uma matriz

In [1]:
from numpy import array

O sistema linearar como por exemplo:

                        1x + 2y + 3z = 11
                        3x + 2y + 1z = 9
                        2x + 3y + 1z = 10

Caso se deseje se utilizar de um sistema 2X2 como:

                        1x + 2y = 10
                        2x - 1y = 5


In [2]:
'''
Este será o formato adotado para a representação de sistemas e, consequentemente, matrizes neste progarama
onde cada linha da matriz é uma lista dentro de uma lista principal

Ou seja, o valor do elemento 1x1 da matriz pode ser acessado como A[0][0]
'''
M = [
    [1, 2, 3, 11],
    [3, 2, 1,  9],
    [2, 3, 1, 10]  
]

## Transformar a matriz em uma matriz triangular

O processo de transformar a matriz em uma matriz triangular é essencial, pois facilita o calculo computacional.
Neste sentido matrizes triangulares são aquelas que seguem o seguinte formato:

                                                    a  b  c

                                                    0  d  e 

                                                    0  0  f 

In [3]:
# transformação e copia da matriz original para que nao haja perdas de informação
A = array(M, dtype=float)
A1 = A.copy()

In [4]:
'''
Antes de qualquer passo, tranformaremos o primeiro digito da primeira linha em 1.
Para essa tranformação, será necessario dividir as linhas da matriz pelo primeiro elemento.
E depois subtrir as linhas entre si, para que o determinante dela se matenha o mesmo, e tenhamos o primeiro 
digito da segunda lnha como 0.

'''
# Dividir todos os elementos da primeira linha pelo elemento 1x1 da matriz: Assim o elemento 1x1 = 1
linha1 = A1[0]/A1[0][0]

#Substituir a linha 1 e subtrair a linha 2 pela linha 1 multiplicada pelo elemento 2x1
A1[0] = linha1
A1[1]= A1[1] - A1[0]*A1[1][0]

### importar a função set_printoptions para que as matrizes não se apresentem em notação científica

In [5]:
from numpy import set_printoptions

In [6]:
#Confira seus resultados e sua nova matriz
set_printoptions(suppress=True, precision=2)
print(linha1)
print("")
print(A1)
print("")

[ 1.  2.  3. 11.]

[[  1.   2.   3.  11.]
 [  0.  -4.  -8. -24.]
 [  0.   0.   0.   0.]]



In [7]:
#subtrair a linha 3 da matriz pela linha 1 multiplicada pelo elemento 3x1
A1[2] = A1[2] - A1[0]*A1[2][0]

In [8]:
#visualize
print(A1)

[[  1.   2.   3.  11.]
 [  0.  -4.  -8. -24.]
 [  0.   0.   0.   0.]]


In [9]:
'''
Da mesma forma, tornaremos 1 o segundo termo da segunda fileira (2x2)
fileira, dividindo a linha por ele mesmo, como fizemos anteriormente.
E subtrairemos a linha 3 pela linha 2.

'''
#Dividir todos os elementos da segunda linha pelo elemento 2x2 da matriz: Assim o elemento 2x2 = 1
linha2 = A1[1]/A1[1][1]

#substituir a linha 2
A1[1] = linha2

#visualize
print(A1)
print("")

#subtrair a linha 3 pela linha 2 multiplicada pelo elemento 3x2
A1[2] = A1[2] - A1[1]*A1[2][1]

#visualize
print(A1)


[[ 1.  2.  3. 11.]
 [-0.  1.  2.  6.]
 [ 0.  0.  0.  0.]]

[[ 1.  2.  3. 11.]
 [-0.  1.  2.  6.]
 [ 0.  0.  0.  0.]]


## Descobir se a função é possivel determinada, possivel indeterminada ou impossivel

In [10]:
def determinante_3x3(M):
    """
    Arg: Matriz triangular
    
    Essa função apenas funciona para matrizes triangulas 3x3, 
    visto que a ultima coluna 
    corrsponde as respostas do sistema
    
    Return: um float do determinante de matriz 
    """
    determinante = M[0][0]
    for linha in range (1, len(M)):
        determinante *= M[linha][linha]
    return determinante

In [11]:
#visualize
print(determinante_3x3(A1))

0.0


In [12]:
def tipo_sistema_3x3(M):
    '''
    Arg: Uma matriz triangular 3X3
    Contem os mesmos requisistos para o calculo da determinante
    Return: Uma string que expressa o tipo do sistema
    
    
    
    '''
    if determinante_3x3(M) == 0:
        if sum(M[0]) or sum(M[1]) or sum(M[2]) == 0:
            return "seu sistema é possivel indeterminado"
        else:
            return "seu sistema é impossivel"
    else:
        return "seu sistema é possivel determinado"
    

In [13]:
#visualize
print(tipo_sistema_3x3(A1))
print(A1)

seu sistema é possivel indeterminado
[[ 1.  2.  3. 11.]
 [-0.  1.  2.  6.]
 [ 0.  0.  0.  0.]]


In [16]:
def respostas_sistema_3x3(M):
    '''
    Arg: Matriz triangular 3X3 
    As mesmas restrições que se aplicam as funções anterores
    Retrun: Dicionario contendo as respostas 
    caso a função seja possivel determinada
    
    '''

    
    if tipo_sistema_3x3(M) == "seu sistema é possivel indeterminado":
        print("Existem infinitas soluções para o seu problema")
    elif tipo_sistema_3x3(M) == "seu sistema é impossivel":
        print("Suas soluções não são possiveis de serem determinadas")
    else:
        respostas = {}
        z = M[2][3] / M[2][2]
        y = (M[1][3] - M[1][2]*z) / M[1][1]
        x = (M[0][3] - M[0][1]*y - M[0][2]*z) / M[0][0]
        
        respostas["x"], respostas["y"], respostas["z"] = x,y,z
        return respostas

In [17]:
#visualize
respostas_sistema_3x3(A1)

Existem infinitas soluções para o seu problema
